import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";
import Footer from "./components/footer";
import { CartProvider } from "./contexts/cartContext";
import ToastProvider from "./components/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Products",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-900/50 h-full`}
      >
        <CartProvider>
          <ToastProvider />
          <Navigation />
          <main className="h-screen flex flex-col overflow-auto scroll-smooth">
            {children}
          </main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
